dicData={'AW cola':['Sodium, carbohydrate',40.61 ],
     'Beijing Beef':['Fat, sodium, cholesterol, carbohydrate, protein', 301.89 ] ,
     'Chow Mein':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium, vitamin D',162.98], 'Fried Rice':['Fat, carbohydrates, protein, calcium, iron, potassium',173.72], 'Hashbrown':['Fat, carbohydrate, protein, potassium',217.39],
     'Honey Walnut Shrimp':['Fat, carbohydrates, protein potassium',271],
     'Kung Pao Chicken':['Fat, carbohydrate,protein, iron, calcium, vitamin D, vitamin B6, magnesium, cobalanin, potassium, vitamin C, sodium,',129],
     'String Bean Chicken Breast':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium',122.99],
     'Super Greens':['Fat, sodium, carbohydrate, protein',367.44],
     'The Original Orange Chicken':['Fat, sodium, cholesterol, carbohydrate, protein,  potassium',323.34],
     'White Steamed Rice':['Fat, carbohydrates, protein, calcium, iron, potassium',129.75],
     'black pepper rice bowl':['Fat, sodium, carbohydrate, protein, potassium, calcium, iron',123.45],
     'burger':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium',221.24],
     'carrot_eggs':['Fat, sodium, cholesterol, carbohydrate, protein, vitamin A, vitamin E',125.86],
     'cheese burger':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium, vitamin D',268.84],
     'chicken waffle':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium, vitamin D',294.19],
     'chicken_nuggets':['Fat, carbohydrate,protein, iron, calcium, vitamin D, vitamin B6, magnesium, cobalanin, potassium',296],
     'chinese_cabbage':['Sodium, carbohydrate, protein,calcium, iron, potassium', 12.86],
     'chinese_sausage':['Fat, sodium, cholesterol, carbohydrate, protein',285.71 ],
     'crispy corn':['Fat, sodium, carbohydrate, protein',440],
     'curry':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium',103.40],
     'french fries':['Fat, sodium, carbohydrate, protein, calcium, iron, potassium',208.57 ],
     'fried chicken':['Fat, carbohydrate,protein, iron, calcium, vitamin D, vitamin B6, magnesium, cobalanin',297],
     'fried_chicken':['Fat, carbohydrate,protein, iron, calcium, vitamin D, vitamin B6, magnesium, cobalanin',297],
     'fried_dumplings':['protein, carbohydrates, fat',356],
     'fried_eggs':['Fat, sodium, cholesterol, carbohydrate, protein, vitamin D, calcium, iron, potassium',195.65],
     'mango chicken pocket':['Fat, sodium, carbohydrate, protein, calcium, iron, potassium',97.73],
     'mozza burger':['carbohydrates, protein, fat, cholesterol, sodium, vitamin A and C, Iron',284.40],
     'mung_bean_sprouts':['Sodium, carbohydrate, protein, calcium, iron, potassium', 20.97],
     'nugget':['fat, cholesterol, sodium, carbohydrates, fiber, protein', 180],
     'perkedel':['Fat, sodium, cholesterol, carbohydrate, protein, calcium, iron, potassium, vitamin D',209.09],
     'rice':['fat, carbs, protein',129],
     'sprite':['Sodium, carbohydrate',41.04],
     'tostitos cheese dip sauce':['Fat, sodium, carbohydrate, protein, potassium, iron',301.20], 'triangle_hash_brown':['Fat, carbohydrate, protein and potassium',217.39],
     'water_spinach':['sodium, carbohydrate, protein, potassium, calcium, iron',19.64]}
